// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"time"
)

type IdpSvcRole struct {
	ID          int64  `json:"id"`
	RoleName    string `json:"role_name"`
	Permissions []byte `json:"permissions"`
}

type IdpSvcUserRole struct {
	UserID    int64     `json:"user_id"`
	RoleID    int64     `json:"role_id"`
	CreatedAt time.Time `json:"created_at"`
}
