// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountTotalNumberOfSessionsPerUser(ctx context.Context) ([]CountTotalNumberOfSessionsPerUserRow, error)
	CreateUserAccount(ctx context.Context, arg CreateUserAccountParams) (IdpSvcUserAccount, error)
	DeleteUserAccountById(ctx context.Context, id int64) error
	DeleteUserAccountByValue(ctx context.Context, username string) error
	FetchDataForSpecificDateRange(ctx context.Context, arg FetchDataForSpecificDateRangeParams) ([]IdpSvcUserAccount, error)
	GetAllUserAccounts(ctx context.Context) ([]IdpSvcUserAccount, error)
	GetUserAccountByEmail(ctx context.Context, email string) (IdpSvcUserAccount, error)
	GetUserAccountById(ctx context.Context, id int64) (IdpSvcUserAccount, error)
	GetUserAccountByUserAccountname(ctx context.Context, username string) (IdpSvcUserAccount, error)
	GetUserAccountWithActiveSessions(ctx context.Context) ([]IdpSvcUserAccount, error)
	GetUserAccountWithBlockedSessions(ctx context.Context) ([]IdpSvcUserAccount, error)
	GetUserAccountWithPermissions(ctx context.Context, permissions string) ([]IdpSvcUserAccount, error)
	GetUserAccountsByAccountStatus(ctx context.Context, accountStatus string) ([]IdpSvcUserAccount, error)
	GetUserAccountsByAccountType(ctx context.Context, accountType int32) ([]IdpSvcUserAccount, error)
	GetUserAccountsByCountryCode(ctx context.Context, countryCode string) ([]IdpSvcUserAccount, error)
	GetUserAccountsByOwner(ctx context.Context, owner string) ([]IdpSvcUserAccount, error)
	GetUserAccountsByRoleId(ctx context.Context, roleID pgtype.Int8) ([]IdpSvcUserAccount, error)
	GetUserAccountsCreatedAfter(ctx context.Context, userCreatedAt time.Time) ([]IdpSvcUserAccount, error)
	GetUserAccountsUpdatedAfter(ctx context.Context, userUpdatedAt time.Time) ([]IdpSvcUserAccount, error)
	ListUserAccounts(ctx context.Context, arg ListUserAccountsParams) ([]ListUserAccountsRow, error)
	OrderResultsByLastLoginTime(ctx context.Context) ([]IdpSvcUserAccount, error)
	UpdateUserAccount(ctx context.Context, arg UpdateUserAccountParams) (IdpSvcUserAccount, error)
}

var _ Querier = (*Queries)(nil)
