// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: refresh_token.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO "idp_svc"."RefreshTokens" (user_id, token, expires_at) VALUES ($1, $2, $3) RETURNING id, user_id, token, expires_at, revoked
`

type CreateRefreshTokenParams struct {
	UserID    int64              `json:"user_id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (IdpSvcRefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.UserID, arg.Token, arg.ExpiresAt)
	var i IdpSvcRefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.Revoked,
	)
	return i, err
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :exec
DELETE FROM "idp_svc"."RefreshTokens" WHERE id = $1
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteRefreshToken, id)
	return err
}

const getRefreshTokenByID = `-- name: GetRefreshTokenByID :one
SELECT id, user_id, token, expires_at, revoked FROM "idp_svc"."RefreshTokens" WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRefreshTokenByID(ctx context.Context, id int64) (IdpSvcRefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByID, id)
	var i IdpSvcRefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.Revoked,
	)
	return i, err
}

const getRefreshTokenByValue = `-- name: GetRefreshTokenByValue :one
SELECT id, user_id, token, expires_at, revoked FROM "idp_svc"."RefreshTokens" WHERE token = $1 LIMIT 1
`

func (q *Queries) GetRefreshTokenByValue(ctx context.Context, token string) (IdpSvcRefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByValue, token)
	var i IdpSvcRefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.Revoked,
	)
	return i, err
}

const listRefreshTokens = `-- name: ListRefreshTokens :many
SELECT id, user_id, token, expires_at, revoked FROM "idp_svc"."RefreshTokens" ORDER BY id LIMIT $1 OFFSET $2
`

type ListRefreshTokensParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListRefreshTokens(ctx context.Context, arg ListRefreshTokensParams) ([]IdpSvcRefreshToken, error) {
	rows, err := q.db.Query(ctx, listRefreshTokens, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdpSvcRefreshToken{}
	for rows.Next() {
		var i IdpSvcRefreshToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.ExpiresAt,
			&i.Revoked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRefreshToken = `-- name: UpdateRefreshToken :one
UPDATE "idp_svc"."RefreshTokens" SET token = COALESCE($2, token), expires_at = COALESCE($3, expires_at) WHERE id = $1 RETURNING token, expires_at
`

type UpdateRefreshTokenParams struct {
	ID        int64              `json:"id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type UpdateRefreshTokenRow struct {
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UpdateRefreshToken(ctx context.Context, arg UpdateRefreshTokenParams) (UpdateRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, updateRefreshToken, arg.ID, arg.Token, arg.ExpiresAt)
	var i UpdateRefreshTokenRow
	err := row.Scan(&i.Token, &i.ExpiresAt)
	return i, err
}
