// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: user_role/rpc_check_if_user_has_role.proto

package user_role

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckIfUserHasRoleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleId int64 `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
}

func (x *CheckIfUserHasRoleRequest) Reset() {
	*x = CheckIfUserHasRoleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_role_rpc_check_if_user_has_role_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckIfUserHasRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIfUserHasRoleRequest) ProtoMessage() {}

func (x *CheckIfUserHasRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_role_rpc_check_if_user_has_role_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIfUserHasRoleRequest.ProtoReflect.Descriptor instead.
func (*CheckIfUserHasRoleRequest) Descriptor() ([]byte, []int) {
	return file_user_role_rpc_check_if_user_has_role_proto_rawDescGZIP(), []int{0}
}

func (x *CheckIfUserHasRoleRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CheckIfUserHasRoleRequest) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type CheckIfUserHasRoleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserRole *UserRole `protobuf:"bytes,1,opt,name=user_role,json=userRole,proto3" json:"user_role,omitempty"`
}

func (x *CheckIfUserHasRoleResponse) Reset() {
	*x = CheckIfUserHasRoleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_role_rpc_check_if_user_has_role_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckIfUserHasRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIfUserHasRoleResponse) ProtoMessage() {}

func (x *CheckIfUserHasRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_role_rpc_check_if_user_has_role_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIfUserHasRoleResponse.ProtoReflect.Descriptor instead.
func (*CheckIfUserHasRoleResponse) Descriptor() ([]byte, []int) {
	return file_user_role_rpc_check_if_user_has_role_proto_rawDescGZIP(), []int{1}
}

func (x *CheckIfUserHasRoleResponse) GetUserRole() *UserRole {
	if x != nil {
		return x.UserRole
	}
	return nil
}

var File_user_role_rpc_check_if_user_has_role_proto protoreflect.FileDescriptor

var file_user_role_rpc_check_if_user_has_role_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x2f, 0x72, 0x70, 0x63, 0x5f,
	0x63, 0x68, 0x65, 0x63, 0x6b, 0x5f, 0x69, 0x66, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x68, 0x61,
	0x73, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62,
	0x1a, 0x19, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x2f, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4d, 0x0a, 0x19, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x49, 0x66, 0x55, 0x73, 0x65, 0x72, 0x48, 0x61, 0x73, 0x52, 0x6f, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x47, 0x0a, 0x1a, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x49, 0x66, 0x55, 0x73, 0x65, 0x72, 0x48, 0x61, 0x73, 0x52, 0x6f, 0x6c, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x52,
	0x6f, 0x6c, 0x65, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x66, 0x61, 0x69, 0x72, 0x2f, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x66, 0x61, 0x69, 0x72, 0x5f, 0x69, 0x64, 0x70, 0x5f, 0x73, 0x76, 0x63, 0x2f,
	0x70, 0x62, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_user_role_rpc_check_if_user_has_role_proto_rawDescOnce sync.Once
	file_user_role_rpc_check_if_user_has_role_proto_rawDescData = file_user_role_rpc_check_if_user_has_role_proto_rawDesc
)

func file_user_role_rpc_check_if_user_has_role_proto_rawDescGZIP() []byte {
	file_user_role_rpc_check_if_user_has_role_proto_rawDescOnce.Do(func() {
		file_user_role_rpc_check_if_user_has_role_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_role_rpc_check_if_user_has_role_proto_rawDescData)
	})
	return file_user_role_rpc_check_if_user_has_role_proto_rawDescData
}

var file_user_role_rpc_check_if_user_has_role_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_user_role_rpc_check_if_user_has_role_proto_goTypes = []interface{}{
	(*CheckIfUserHasRoleRequest)(nil),  // 0: pb.CheckIfUserHasRoleRequest
	(*CheckIfUserHasRoleResponse)(nil), // 1: pb.CheckIfUserHasRoleResponse
	(*UserRole)(nil),                   // 2: pb.UserRole
}
var file_user_role_rpc_check_if_user_has_role_proto_depIdxs = []int32{
	2, // 0: pb.CheckIfUserHasRoleResponse.user_role:type_name -> pb.UserRole
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_user_role_rpc_check_if_user_has_role_proto_init() }
func file_user_role_rpc_check_if_user_has_role_proto_init() {
	if File_user_role_rpc_check_if_user_has_role_proto != nil {
		return
	}
	file_user_role_user_role_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_user_role_rpc_check_if_user_has_role_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckIfUserHasRoleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_role_rpc_check_if_user_has_role_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckIfUserHasRoleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_role_rpc_check_if_user_has_role_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_role_rpc_check_if_user_has_role_proto_goTypes,
		DependencyIndexes: file_user_role_rpc_check_if_user_has_role_proto_depIdxs,
		MessageInfos:      file_user_role_rpc_check_if_user_has_role_proto_msgTypes,
	}.Build()
	File_user_role_rpc_check_if_user_has_role_proto = out.File
	file_user_role_rpc_check_if_user_has_role_proto_rawDesc = nil
	file_user_role_rpc_check_if_user_has_role_proto_goTypes = nil
	file_user_role_rpc_check_if_user_has_role_proto_depIdxs = nil
}
